### PR TITLE
Changed syntax in some anonymous functions.

### PR DESCRIPTION
**Pull request by jherrlin**
What are the real differences here?
Is is just syntax?

### CODE REVIEW

**Comment by Leitet** [comment]
It will work, however:

`courseCode.forEach((node) => { console.log(node); });` is the equality to:

`courseCode.forEach(function(node) {
   console.log(node);
   return;
});`

while this:
`courseCode.forEach((node) => console.log(node));``

is equal to:

`courseCode.forEach(function(node) {
  return console.log(node);
});`

So, omitting the brackets will execute and return the statement instead of just executing it. Howerver, in this case console.log is always returning "undefined" so in the case of console.log thoose are basically equal. Ommiting is a lot cleaner though.

**Comment by jherrlin** [comment]
Thx!

Okey, so if i understands it correct then:

WITH `{}` you can have many statements within the anonymous function, and WITHOUT `{}` you can only have one expression?

**Comment by jherrlin** [comment]
Example:

``` javascript
"use strict";

const createStudent = function(name, age) {
    return {
        name : name,
        age  : age,

        greet: function(){
            console.log(this.name + ' is greeting you!');
        }
    };
}

const students = [];
students.push(createStudent('Ellen', 30));
students.push(createStudent('Peter', 32));

// This way we can have many statements within the anonymous function.                                                                                       
students.forEach((s) => {
    console.log(s);
    s.greet();
});

console.log('\n-------------------\n');

// This way we can only handle one expression.                                                                                                               
students.forEach((s) => s.greet());
```

**Comment by Leitet** [comment]
Correct.

**Pull request closed without merging**
